config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'projects#index'

  resources :projects do
    resources :tasks
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks, dependent: :destroy

  validates :title, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project

  validates :title, :priority, presence: true

  def shift_priority
    project.tasks.where('priority > ?', priority).each do |task|
      task.priority -= 1
      task.save
    end
  end

  def drag_n_drop_switch(current_priority)
    tasks = if current_priority > priority
              priority_switch = -1
              project.tasks.where('priority between ? and ?', priority + 1, current_priority)
            else
              priority_switch = 1
              project.tasks.where('priority between ? and ?', current_priority, priority - 1)
            end

    tasks.each do |task|
      task.priority += priority_switch
      task.save
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects.all.includes(:tasks)
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:update, :destroy]

  # POST /tasks
  # POST /tasks.json
  def create
    set_project
    @task = @project.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.json { render :show, status: :created }
      else
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    if params['task']['drag_n_drop']
      @task.drag_n_drop_switch(params['task']['priority'])
    end

    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.shift_priority
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      set_project
      @task = @project.tasks.find(params[:id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :completed, :project_id, :priority)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.haml
.navbar.navbar-default
  .navbar-header
    .navbar-brand
      .home-title
        Task Manager
  .navbar-collapse.collapse.navbar-inverse-collapse
    %ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        %li= link_to current_user.email, edit_user_registration_path
        %li= link_to 'Sign out', destroy_user_session_path, :method => 'delete'
      - else
        - if current_page? new_user_registration_path
          %li= link_to 'Sign in', new_user_session_path
        - else
          %li= link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Todo
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    - unless notice.blank?
      %p.notice= notice
    - unless alert.blank?  
      %p.alert= alert
    = yield

app/views/projects/_form.html.haml
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
#projects-wrap.center
:javascript
  $(function() {
  // Blog is the app name
  window.router = new Todo.Routers.ProjectsRouter({projects: #{@projects.to_json({:include => :tasks}).html_safe}});
  Backbone.history.start();
  })

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @project.title

= link_to 'Edit', edit_project_path(@project)
\|
= link_to 'Back', projects_path

app/views/tasks/_form.html.haml
= form_for @task do |f|
  - if @task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      %ul
        - @task.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :completed
    = f.check_box :completed
  .field
    = f.label :project
    = f.text_field :project
  .actions
    = f.submit 'Save'

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Show', @task
\|
= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
%h1 Listing tasks

%table
  %tr
    %th Title
    %th Completed
    %th Project
    %th
    %th
    %th

  - @tasks.each do |task|
    %tr
      %td= task.title
      %td= task.completed
      %td= task.project
      %td= link_to 'Show', task
      %td= link_to 'Edit', edit_task_path(task)
      %td= link_to 'Destroy', task, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Task', new_task_path

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @task.title
%p
  %b Completed:
  = @task.completed
%p
  %b Project:
  = @task.project

= link_to 'Edit', edit_task_path(@task)
\|
= link_to 'Back', tasks_path